In [60]:
# We will define a toss win as a team winning both the toss AND the match.
## This cell will compute tosses.

import pandas as pd

df = pd.read_csv("data/t20i_matches_clean.csv")

total_matches=len(df)

match_and_toss=len(df[(df['toss_winner'] == df['winner'])])

toss_pct=round((match_and_toss / total_matches)*100 , 3)

print('The percent of matches won by the team who won the toss is '+str(toss_pct) +'% overall')

The percent of matches won by the team who won the toss is 50.204% overall

no significant effect

In [61]:
##This cell will compute whether toss decision has an effect

bat=len(df[(df['toss_decision'] == 'bat')])
ball=len(df[(df['toss_decision'] == 'field')])

bat_win=len(df[
    (df['toss_decision'] == 'bat') &
    (df['toss_winner'] == df['winner'])  
               ])
ball_win=len(df[
    (df['toss_decision'] == 'field') &
    (df['toss_winner'] == df['winner'])  
               ])

bat_win_pct=round((bat_win/ bat )*100 , 3)
ball_win_pct=round((ball_win/ ball )*100 , 3)

print('The percentage of matches won by the team who won the toss and elected to bat is '+str(bat_win_pct)+'%')
print('The percentage of matches won by the team who won the toss and elected to field is '+str(ball_win_pct)+'%')

The percentage of matches won by the team who won the toss and elected to bat is 49.077%
The percentage of matches won by the team who won the toss and elected to field is 51.167%

no significant effect

In [62]:
#This one will look at venues
# add helper column: did toss winner also win match?
df["toss_win"] = (df["toss_winner"] == df["winner"])

# group by venue
venue_stats = (
    df.groupby("venue")
      .agg(
          matches=("venue", "count"),
          toss_win_rate=("toss_win", "mean")
      )
      .reset_index()
)

# convert rate to percentage
venue_stats["toss_win_rate"] = venue_stats["toss_win_rate"] * 100

# drop small sample venues
venue_stats = venue_stats[venue_stats["matches"] >= 10]

# sort by toss impact
venue_stats = venue_stats.sort_values(by="toss_win_rate", ascending=False)

venue_stats.head(100)

                                            venue  matches  toss_win_rate
128           King George V Sports Ground, Castel       14      78.571429
123                   Kensington Oval, Bridgetown       16      75.000000
68                           Entebbe Cricket Oval       19      73.684211
268                            TCA Oval, Blantyre       14      71.428571
76                        Gaddafi Stadium, Lahore       14      71.428571
..                                            ...      ...            ...
209                           Roma Cricket Ground       12      25.000000
236                    Simar Cricket Ground, Rome       12      25.000000
210  Royal Brussels Cricket Club Ground, Waterloo       10      20.000000
24                         Bellerive Oval, Hobart       11      18.181818
3                                   Adelaide Oval       12       8.333333

[96 rows x 3 columns]

In [64]:
#we will count matches played for each team

played = {}

for col, row in df.iterrows():
    team1 = row["team1"]
    team2 = row["team2"]

    if team1 not in played:
        played[team1] = 0
    played[team1] += 1

    if team2 not in played:
        played[team2] = 0
    played[team2] += 1

print(played)

#count wins

won={}
for col, row in df.iterrows():
    team = row["winner"]

    if team not in won:
        won[team] = 0
    won[team] += 1

for team in played:
    if team not in won:
        won[team]=0
    
#compute win percent
wpct={}
for team in played:
    if team not in won:
        wpct[team]=0
    else:
        wpct[team]=(won[team] / played[team]) 

wpct

{'New Zealand': 223, 'Australia': 207, 'England': 199, 'South Africa': 203, 'Sri Lanka': 200, 'Pakistan': 262, 'India': 237, 'West Indies': 216, 'Kenya': 92, 'Bangladesh': 185, 'Scotland': 85, 'Zimbabwe': 161, 'Bermuda': 45, 'Netherlands': 108, 'Ireland': 134, 'Canada': 69, 'Hong Kong': 106, 'Nepal': 100, 'United Arab Emirates': 117, 'Papua New Guinea': 57, 'Oman': 95, 'ICC World XI': 4, 'United States of America': 48, 'Vanuatu': 31, 'Philippines': 33, 'Ghana': 37, 'Namibia': 82, 'Uganda': 102, 'Botswana': 45, 'Nigeria': 79, 'Germany': 56, 'Italy': 31, 'Guernsey': 33, 'Jersey': 44, 'Norway': 43, 'Denmark': 39, 'Malaysia': 98, 'Thailand': 50, 'Maldives': 37, 'Kuwait': 64, 'Singapore': 61, 'Qatar': 52, 'Cayman Islands': 35, 'Spain': 36, 'Portugal': 30, 'Gibraltar': 47, 'Bhutan': 30, 'Bahrain': 90, 'Saudi Arabia': 48, 'Iran': 1, 'Isle of Man': 19, 'Belgium': 35, 'Luxembourg': 40, 'Czech Republic': 35, 'Bulgaria': 46, 'Romania': 53, 'Austria': 58, 'Greece': 9, 'Serbia': 32, 'Malta': 66, 'France': 32, 'Sweden': 28, 'Rwanda': 83, 'Finland': 29, 'Hungary': 36, 'Estonia': 29, 'Cyprus': 31, 'Seychelles': 12, 'Malawi': 36, 'Lesotho': 11, 'Swaziland': 5, 'Sierra Leone': 29, 'Switzerland': 28, 'Tanzania': 67, 'Mozambique': 21, 'Cameroon': 15, 'Belize': 12, 'Panama': 22, 'Bahamas': 28, 'Argentina': 21, 'Israel': 8, 'Turkey': 15, 'Croatia': 23, 'Slovenia': 15, 'Samoa': 23, 'Cook Islands': 16, 'Fiji': 11, 'Japan': 46, 'Indonesia': 75, 'South Korea': 17, 'Mali': 9, 'St Helena': 8, 'Gambia': 9, 'Eswatini': 13, 'China': 9, 'Myanmar': 25, 'Mongolia': 13, 'Chile': 2, 'Mexico': 18, 'Cambodia': 28, 'Costa Rica': 8, 'Brazil': 9, 'Ivory Coast': 5, 'Suriname': 8, 'Turks and Caicos Island': 4, 'Timor-Leste': 8}

{'New Zealand': 0.5605381165919282,
 'Australia': 0.5845410628019324,
 'England': 0.5477386934673367,
 'South Africa': 0.541871921182266,
 'Sri Lanka': 0.45,
 'Pakistan': 0.5954198473282443,
 'India': 0.6962025316455697,
 'West Indies': 0.4398148148148148,
 'Kenya': 0.532608695652174,
 'Bangladesh': 0.3891891891891892,
 'Scotland': 0.49411764705882355,
 'Zimbabwe': 0.4161490683229814,
 'Bermuda': 0.6888888888888889,
 'Netherlands': 0.5277777777777778,
 'Ireland': 0.4626865671641791,
 'Canada': 0.5942028985507246,
 'Hong Kong': 0.4716981132075472,
 'Nepal': 0.62,
 'United Arab Emirates': 0.5641025641025641,
 'Papua New Guinea': 0.5087719298245614,
 'Oman': 0.49473684210526314,
 'ICC World XI': 0.25,
 'United States of America': 0.5833333333333334,
 'Vanuatu': 0.3870967741935484,
 'Philippines': 0.42424242424242425,
 'Ghana': 0.35135135135135137,
 'Namibia': 0.6097560975609756,
 'Uganda': 0.7941176470588235,
 'Botswana': 0.3111111111111111,
 'Nigeria': 0.46835443037974683,
 'Germany': 0.5892857142857143,
 'Italy': 0.6451612903225806,
 'Guernsey': 0.5151515151515151,
 'Jersey': 0.6590909090909091,
 'Norway': 0.5348837209302325,
 'Denmark': 0.4358974358974359,
 'Malaysia': 0.5714285714285714,
 'Thailand': 0.42,
 'Maldives': 0.24324324324324326,
 'Kuwait': 0.59375,
 'Singapore': 0.36065573770491804,
 'Qatar': 0.5,
 'Cayman Islands': 0.4,
 'Spain': 0.8055555555555556,
 'Portugal': 0.7,
 'Gibraltar': 0.3191489361702128,
 'Bhutan': 0.3333333333333333,
 'Bahrain': 0.6222222222222222,
 'Saudi Arabia': 0.5416666666666666,
 'Iran': 0.0,
 'Isle of Man': 0.5263157894736842,
 'Belgium': 0.5714285714285714,
 'Luxembourg': 0.325,
 'Czech Republic': 0.45714285714285713,
 'Bulgaria': 0.34782608695652173,
 'Romania': 0.6037735849056604,
 'Austria': 0.7413793103448276,
 'Greece': 0.1111111111111111,
 'Serbia': 0.28125,
 'Malta': 0.4090909090909091,
 'France': 0.46875,
 'Sweden': 0.39285714285714285,
 'Rwanda': 0.2891566265060241,
 'Finland': 0.4482758620689655,
 'Hungary': 0.4722222222222222,
 'Estonia': 0.3793103448275862,
 'Cyprus': 0.6129032258064516,
 'Seychelles': 0.16666666666666666,
 'Malawi': 0.3888888888888889,
 'Lesotho': 0.18181818181818182,
 'Swaziland': 0.0,
 'Sierra Leone': 0.41379310344827586,
 'Switzerland': 0.6428571428571429,
 'Tanzania': 0.5671641791044776,
 'Mozambique': 0.38095238095238093,
 'Cameroon': 0.13333333333333333,
 'Belize': 0.25,
 'Panama': 0.3181818181818182,
 'Bahamas': 0.2857142857142857,
 'Argentina': 0.47619047619047616,
 'Israel': 0.375,
 'Turkey': 0.13333333333333333,
 'Croatia': 0.17391304347826086,
 'Slovenia': 0.06666666666666667,
 'Samoa': 0.21739130434782608,
 'Cook Islands': 0.5,
 'Fiji': 0.5454545454545454,
 'Japan': 0.6521739130434783,
 'Indonesia': 0.49333333333333335,
 'South Korea': 0.11764705882352941,
 'Mali': 0.0,
 'St Helena': 0.25,
 'Gambia': 0.1111111111111111,
 'Eswatini': 0.46153846153846156,
 'China': 0.1111111111111111,
 'Myanmar': 0.2,
 'Mongolia': 0.0,
 'Chile': 0.0,
 'Mexico': 0.4444444444444444,
 'Cambodia': 0.42857142857142855,
 'Costa Rica': 0.25,
 'Brazil': 0.3333333333333333,
 'Ivory Coast': 0.0,
 'Suriname': 0.25,
 'Turks and Caicos Island': 0.25,
 'Timor-Leste': 0.0}

In [69]:
##compile the 3 dicts into one dataframe
rows=[]
for team in played:
    r = {
    "Team": team,
    "Appearances": played[team],
    "Wins": won[team],
    "Win Rate": wpct[team]
}
    rows.append(r)

df1=pd.DataFrame(rows)
df1

                        Team  Appearances  Wins  Win Rate
0                New Zealand          223   125  0.560538
1                  Australia          207   121  0.584541
2                    England          199   109  0.547739
3               South Africa          203   110  0.541872
4                  Sri Lanka          200    90  0.450000
..                       ...          ...   ...       ...
101                   Brazil            9     3  0.333333
102              Ivory Coast            5     0  0.000000
103                 Suriname            8     2  0.250000
104  Turks and Caicos Island            4     1  0.250000
105              Timor-Leste            8     0  0.000000

[106 rows x 4 columns]

In [70]:
#sort dataframe for readibility

df1=df1.sort_values(by='Win Rate', ascending=False)

df1.head(40)

                        Team  Appearances  Wins  Win Rate
43                     Spain           36    29  0.805556
27                    Uganda          102    81  0.794118
56                   Austria           58    43  0.741379
44                  Portugal           30    21  0.700000
6                      India          237   165  0.696203
12                   Bermuda           45    31  0.688889
33                    Jersey           44    29  0.659091
87                     Japan           46    30  0.652174
31                     Italy           31    20  0.645161
72               Switzerland           28    18  0.642857
47                   Bahrain           90    56  0.622222
17                     Nepal          100    62  0.620000
66                    Cyprus           31    19  0.612903
26                   Namibia           82    50  0.609756
55                   Romania           53    32  0.603774
5                   Pakistan          262   156  0.595420
15                    Canada           69    41  0.594203
39                    Kuwait           64    38  0.593750
30                   Germany           56    33  0.589286
1                  Australia          207   121  0.584541
22  United States of America           48    28  0.583333
36                  Malaysia           98    56  0.571429
51                   Belgium           35    20  0.571429
73                  Tanzania           67    38  0.567164
18      United Arab Emirates          117    66  0.564103
0                New Zealand          223   125  0.560538
2                    England          199   109  0.547739
86                      Fiji           11     6  0.545455
3               South Africa          203   110  0.541872
48              Saudi Arabia           48    26  0.541667
34                    Norway           43    23  0.534884
8                      Kenya           92    49  0.532609
13               Netherlands          108    57  0.527778
50               Isle of Man           19    10  0.526316
32                  Guernsey           33    17  0.515152
19          Papua New Guinea           57    29  0.508772
85              Cook Islands           16     8  0.500000
41                     Qatar           52    26  0.500000
20                      Oman           95    47  0.494737
10                  Scotland           85    42  0.494118

In [71]:
matchupnum = {}
h2h_wins = {}

for i, row in df.iterrows():
    team1 = row["team1"]
    team2 = row["team2"]
    winner = row["winner"]

    matchup = tuple(sorted([team1, team2]))

    if matchup not in matchupnum:
        matchupnum[matchup] = 0
    matchupnum[matchup] += 1

    if matchup not in h2h_wins:
        h2h_wins[matchup] = {
            matchup[0]: 0,
            matchup[1]: 0
        }

    if winner in h2h_wins[matchup]:
        h2h_wins[matchup][winner] += 1

In [77]:
#now we want to see the win rate for each h2h
h2h_rates = {}

for matchup in matchupnum:
    total_matches = matchupnum[matchup]
    team_a, team_b = matchup

    wins_a = h2h_wins[matchup][team_a]
    wins_b = h2h_wins[matchup][team_b]

    h2h_rates[matchup] = {
        team_a: wins_a / total_matches,
        team_b: wins_b / total_matches
    }
h2h_rates

{('Australia', 'New Zealand'): {'Australia': 0.75, 'New Zealand': 0.25},
 ('Australia', 'England'): {'Australia': 0.5, 'England': 0.5},
 ('New Zealand', 'South Africa'): {'New Zealand': 0.3888888888888889,
  'South Africa': 0.6111111111111112},
 ('Australia', 'South Africa'): {'Australia': 0.6785714285714286,
  'South Africa': 0.32142857142857145},
 ('England', 'Sri Lanka'): {'England': 0.7142857142857143,
  'Sri Lanka': 0.2857142857142857},
 ('England', 'Pakistan'): {'England': 0.6896551724137931,
  'Pakistan': 0.3103448275862069},
 ('India', 'South Africa'): {'India': 0.6, 'South Africa': 0.4},
 ('New Zealand', 'Sri Lanka'): {'New Zealand': 0.64, 'Sri Lanka': 0.36},
 ('England', 'West Indies'): {'England': 0.5135135135135135,
  'West Indies': 0.4864864864864865},
 ('Bangladesh', 'Kenya'): {'Bangladesh': 1.0, 'Kenya': 0.0},
 ('Bangladesh', 'Pakistan'): {'Bangladesh': 0.19230769230769232,
  'Pakistan': 0.8076923076923077},
 ('Kenya', 'Pakistan'): {'Kenya': 0.0, 'Pakistan': 1.0},
 ('South Africa', 'West Indies'): {'South Africa': 0.46153846153846156,
  'West Indies': 0.5384615384615384},
 ('Kenya', 'New Zealand'): {'Kenya': 0.0, 'New Zealand': 1.0},
 ('Pakistan', 'Scotland'): {'Pakistan': 1.0, 'Scotland': 0.0},
 ('Australia', 'Zimbabwe'): {'Australia': 0.6666666666666666,
  'Zimbabwe': 0.3333333333333333},
 ('England', 'Zimbabwe'): {'England': 1.0, 'Zimbabwe': 0.0},
 ('Bangladesh', 'West Indies'): {'Bangladesh': 0.4, 'West Indies': 0.6},
 ('Kenya', 'Sri Lanka'): {'Kenya': 0.0, 'Sri Lanka': 1.0},
 ('Bangladesh', 'South Africa'): {'Bangladesh': 0.0, 'South Africa': 1.0},
 ('Australia', 'Bangladesh'): {'Australia': 0.6363636363636364,
  'Bangladesh': 0.36363636363636365},
 ('India', 'New Zealand'): {'India': 0.5454545454545454,
  'New Zealand': 0.45454545454545453},
 ('England', 'South Africa'): {'England': 0.48148148148148145,
  'South Africa': 0.5185185185185185},
 ('Pakistan', 'Sri Lanka'): {'Pakistan': 0.5769230769230769,
  'Sri Lanka': 0.4230769230769231},
 ('Bangladesh', 'Sri Lanka'): {'Bangladesh': 0.4090909090909091,
  'Sri Lanka': 0.5909090909090909},
 ('England', 'New Zealand'): {'England': 0.6153846153846154,
  'New Zealand': 0.38461538461538464},
 ('Australia', 'Pakistan'): {'Australia': 0.5384615384615384,
  'Pakistan': 0.46153846153846156},
 ('England', 'India'): {'England': 0.41379310344827586,
  'India': 0.5862068965517241},
 ('Australia', 'Sri Lanka'): {'Australia': 0.6, 'Sri Lanka': 0.4},
 ('New Zealand', 'Pakistan'): {'New Zealand': 0.48936170212765956,
  'Pakistan': 0.5106382978723404},
 ('Australia', 'India'): {'Australia': 0.35294117647058826,
  'India': 0.6470588235294118},
 ('India', 'Pakistan'): {'India': 0.8, 'Pakistan': 0.2},
 ('Australia', 'West Indies'): {'Australia': 0.5925925925925926,
  'West Indies': 0.4074074074074074},
 ('Bermuda', 'Scotland'): {'Bermuda': 0.0, 'Scotland': 1.0},
 ('Netherlands', 'Scotland'): {'Netherlands': 0.4375, 'Scotland': 0.5625},
 ('Ireland', 'Kenya'): {'Ireland': 1.0, 'Kenya': 0.0},
 ('New Zealand', 'West Indies'): {'New Zealand': 0.6842105263157895,
  'West Indies': 0.3157894736842105},
 ('India', 'Sri Lanka'): {'India': 0.7, 'Sri Lanka': 0.3},
 ('England', 'Netherlands'): {'England': 0.0, 'Netherlands': 1.0},
 ('New Zealand', 'Scotland'): {'New Zealand': 1.0, 'Scotland': 0.0},
 ('Bangladesh', 'India'): {'Bangladesh': 0.05555555555555555,
  'India': 0.9444444444444444},
 ('Scotland', 'South Africa'): {'Scotland': 0.0, 'South Africa': 1.0},
 ('Bangladesh', 'Ireland'): {'Bangladesh': 0.5, 'Ireland': 0.5},
 ('Netherlands', 'Pakistan'): {'Netherlands': 0.0, 'Pakistan': 1.0},
 ('India', 'Ireland'): {'India': 1.0, 'Ireland': 0.0},
 ('Sri Lanka', 'West Indies'): {'Sri Lanka': 0.5555555555555556,
  'West Indies': 0.4444444444444444},
 ('Ireland', 'New Zealand'): {'Ireland': 0.0, 'New Zealand': 1.0},
 ('India', 'West Indies'): {'India': 0.6551724137931034,
  'West Indies': 0.3448275862068966},
 ('Ireland', 'Sri Lanka'): {'Ireland': 0.0, 'Sri Lanka': 1.0},
 ('Ireland', 'Pakistan'): {'Ireland': 0.2, 'Pakistan': 0.8},
 ('Pakistan', 'South Africa'): {'Pakistan': 0.5384615384615384,
  'South Africa': 0.46153846153846156},
 ('Bangladesh', 'New Zealand'): {'Bangladesh': 0.21052631578947367,
  'New Zealand': 0.7894736842105263},
 ('Canada', 'Netherlands'): {'Canada': 0.25, 'Netherlands': 0.75},
 ('Canada', 'Kenya'): {'Canada': 0.25, 'Kenya': 0.75},
 ('Ireland', 'Scotland'): {'Ireland': 0.7, 'Scotland': 0.3},
 ('Ireland', 'Netherlands'): {'Ireland': 0.5, 'Netherlands': 0.5},
 ('West Indies', 'Zimbabwe'): {'West Indies': 0.75, 'Zimbabwe': 0.25},
 ('Ireland', 'West Indies'): {'Ireland': 0.42857142857142855,
  'West Indies': 0.5714285714285714},
 ('Sri Lanka', 'Zimbabwe'): {'Sri Lanka': 0.7, 'Zimbabwe': 0.3},
 ('New Zealand', 'Zimbabwe'): {'New Zealand': 1.0, 'Zimbabwe': 0.0},
 ('India', 'Zimbabwe'): {'India': 0.7692307692307693,
  'Zimbabwe': 0.23076923076923078},
 ('South Africa', 'Zimbabwe'): {'South Africa': 1.0, 'Zimbabwe': 0.0},
 ('Pakistan', 'West Indies'): {'Pakistan': 0.8095238095238095,
  'West Indies': 0.19047619047619047},
 ('Pakistan', 'Zimbabwe'): {'Pakistan': 0.8636363636363636,
  'Zimbabwe': 0.13636363636363635},
 ('Canada', 'Ireland'): {'Canada': 0.5, 'Ireland': 0.5},
 ('Canada', 'Scotland'): {'Canada': 0.0, 'Scotland': 1.0},
 ('Bangladesh', 'Netherlands'): {'Bangladesh': 0.8571428571428571,
  'Netherlands': 0.14285714285714285},
 ('Australia', 'Ireland'): {'Australia': 1.0, 'Ireland': 0.0},
 ('South Africa', 'Sri Lanka'): {'South Africa': 0.7058823529411765,
  'Sri Lanka': 0.29411764705882354},
 ('Kenya', 'Netherlands'): {'Kenya': 0.5, 'Netherlands': 0.5},
 ('Bangladesh', 'Zimbabwe'): {'Bangladesh': 0.6666666666666666,
  'Zimbabwe': 0.3333333333333333},
 ('Kenya', 'Scotland'): {'Kenya': 0.5, 'Scotland': 0.5},
 ('Hong Kong', 'Nepal'): {'Hong Kong': 0.5, 'Nepal': 0.5},
 ('Ireland', 'Zimbabwe'): {'Ireland': 0.5, 'Zimbabwe': 0.5},
 ('Netherlands', 'United Arab Emirates'): {'Netherlands': 0.7142857142857143,
  'United Arab Emirates': 0.2857142857142857},
 ('Bangladesh', 'Nepal'): {'Bangladesh': 1.0, 'Nepal': 0.0},
 ('Netherlands', 'Zimbabwe'): {'Netherlands': 0.5, 'Zimbabwe': 0.5},
 ('Ireland', 'United Arab Emirates'): {'Ireland': 0.36363636363636365,
  'United Arab Emirates': 0.6363636363636364},
 ('Bangladesh', 'Hong Kong'): {'Bangladesh': 0.5, 'Hong Kong': 0.5},
 ('United Arab Emirates', 'Zimbabwe'): {'United Arab Emirates': 0.0,
  'Zimbabwe': 1.0},
 ('Netherlands', 'Sri Lanka'): {'Netherlands': 0.0, 'Sri Lanka': 1.0},
 ('Netherlands', 'South Africa'): {'Netherlands': 0.3333333333333333,
  'South Africa': 0.6666666666666666},
 ('Netherlands', 'New Zealand'): {'Netherlands': 0.0, 'New Zealand': 1.0},
 ('Nepal', 'Netherlands'): {'Nepal': 0.45454545454545453,
  'Netherlands': 0.5454545454545454},
 ('Scotland', 'United Arab Emirates'): {'Scotland': 0.6666666666666666,
  'United Arab Emirates': 0.3333333333333333},
 ('Ireland', 'Nepal'): {'Ireland': 1.0, 'Nepal': 0.0},
 ('Ireland', 'Papua New Guinea'): {'Ireland': 0.3333333333333333,
  'Papua New Guinea': 0.6666666666666666},
 ('Nepal', 'Papua New Guinea'): {'Nepal': 0.6666666666666666,
  'Papua New Guinea': 0.3333333333333333},
 ('Hong Kong', 'Ireland'): {'Hong Kong': 0.5, 'Ireland': 0.5},
 ('Hong Kong', 'Scotland'): {'Hong Kong': 0.2, 'Scotland': 0.8},
 ('Hong Kong', 'Oman'): {'Hong Kong': 0.125, 'Oman': 0.875},
 ('Oman', 'United Arab Emirates'): {'Oman': 0.5454545454545454,
  'United Arab Emirates': 0.45454545454545453},
 ('Hong Kong', 'United Arab Emirates'): {'Hong Kong': 0.3333333333333333,
  'United Arab Emirates': 0.6666666666666666},
 ('Sri Lanka', 'United Arab Emirates'): {'Sri Lanka': 1.0,
  'United Arab Emirates': 0.0},
 ('Bangladesh', 'United Arab Emirates'): {'Bangladesh': 0.6666666666666666,
  'United Arab Emirates': 0.3333333333333333},
 ('Pakistan', 'United Arab Emirates'): {'Pakistan': 1.0,
  'United Arab Emirates': 0.0},
 ('India', 'United Arab Emirates'): {'India': 1.0,
  'United Arab Emirates': 0.0},
 ('Hong Kong', 'Zimbabwe'): {'Hong Kong': 0.0, 'Zimbabwe': 1.0},
 ('Ireland', 'Oman'): {'Ireland': 0.6666666666666666,
  'Oman': 0.3333333333333333},
 ('Scotland', 'Zimbabwe'): {'Scotland': 0.2, 'Zimbabwe': 0.8},
 ('Bangladesh', 'Oman'): {'Bangladesh': 1.0, 'Oman': 0.0},
 ('Netherlands', 'Oman'): {'Netherlands': 0.6666666666666666,
  'Oman': 0.3333333333333333},
 ('Hong Kong', 'Netherlands'): {'Hong Kong': 0.3333333333333333,
  'Netherlands': 0.6666666666666666},
 ('Oman', 'Scotland'): {'Oman': 0.0, 'Scotland': 1.0},
 ('Papua New Guinea', 'United Arab Emirates'): {'Papua New Guinea': 0.0,
  'United Arab Emirates': 1.0},
 ('ICC World XI', 'Pakistan'): {'ICC World XI': 0.3333333333333333,
  'Pakistan': 0.6666666666666666},
 ('ICC World XI', 'West Indies'): {'ICC World XI': 0.0, 'West Indies': 1.0},
 ('Australia', 'United Arab Emirates'): {'Australia': 1.0,
  'United Arab Emirates': 0.0},
 ('Nepal', 'United Arab Emirates'): {'Nepal': 0.5454545454545454,
  'United Arab Emirates': 0.45454545454545453},
 ('United Arab Emirates',
  'United States of America'): {'United Arab Emirates': 0.6666666666666666, 'United States of America': 0.3333333333333333},
 ('Papua New Guinea', 'Vanuatu'): {'Papua New Guinea': 1.0, 'Vanuatu': 0.0},
 ('Papua New Guinea', 'Philippines'): {'Papua New Guinea': 1.0,
  'Philippines': 0.0},
 ('Philippines', 'Vanuatu'): {'Philippines': 0.5, 'Vanuatu': 0.5},
 ('Ghana', 'Namibia'): {'Ghana': 0.0, 'Namibia': 1.0},
 ('Botswana', 'Uganda'): {'Botswana': 0.0, 'Uganda': 1.0},
 ('Botswana', 'Nigeria'): {'Botswana': 0.16666666666666666,
  'Nigeria': 0.8333333333333334},
 ('Ghana', 'Kenya'): {'Ghana': 0.0, 'Kenya': 1.0},
 ('Namibia', 'Uganda'): {'Namibia': 0.8888888888888888,
  'Uganda': 0.1111111111111111},
 ('Kenya', 'Uganda'): {'Kenya': 0.26666666666666666,
  'Uganda': 0.7333333333333333},
 ('Botswana', 'Namibia'): {'Botswana': 0.0, 'Namibia': 1.0},
 ('Ghana', 'Nigeria'): {'Ghana': 0.0, 'Nigeria': 1.0},
 ('Ghana', 'Uganda'): {'Ghana': 0.0, 'Uganda': 1.0},
 ('Germany', 'Italy'): {'Germany': 0.5, 'Italy': 0.5},
 ('Germany', 'Guernsey'): {'Germany': 0.5, 'Guernsey': 0.5},
 ('Guernsey', 'Italy'): {'Guernsey': 0.0, 'Italy': 1.0},
 ('Jersey', 'Norway'): {'Jersey': 1.0, 'Norway': 0.0},
 ('Denmark', 'Jersey'): {'Denmark': 0.0, 'Jersey': 1.0},
 ('Denmark', 'Norway'): {'Denmark': 0.6666666666666666,
  'Norway': 0.3333333333333333},
 ('Italy', 'Jersey'): {'Italy': 0.25, 'Jersey': 0.75},
 ('Denmark', 'Germany'): {'Denmark': 0.0, 'Germany': 1.0},
 ('Guernsey', 'Norway'): {'Guernsey': 0.6666666666666666,
  'Norway': 0.3333333333333333},
 ('Germany', 'Norway'): {'Germany': 0.6, 'Norway': 0.4},
 ('Denmark', 'Guernsey'): {'Denmark': 0.0, 'Guernsey': 1.0},
 ('Denmark', 'Italy'): {'Denmark': 0.25, 'Italy': 0.75},
 ('Germany', 'Jersey'): {'Germany': 0.25, 'Jersey': 0.75},
 ('Malaysia', 'Thailand'): {'Malaysia': 1.0, 'Thailand': 0.0},
 ('Maldives', 'Thailand'): {'Maldives': 0.3333333333333333,
  'Thailand': 0.6666666666666666},
 ('Malaysia', 'Nepal'): {'Malaysia': 0.0, 'Nepal': 1.0},
 ('Kuwait', 'Malaysia'): {'Kuwait': 0.3333333333333333,
  'Malaysia': 0.6666666666666666},
 ('Qatar', 'Singapore'): {'Qatar': 0.75, 'Singapore': 0.25},
 ('Nepal', 'Qatar'): {'Nepal': 0.75, 'Qatar': 0.25},
 ('Kuwait', 'Qatar'): {'Kuwait': 0.7142857142857143,
  'Qatar': 0.2857142857142857},
 ('Malaysia', 'Singapore'): {'Malaysia': 0.75, 'Singapore': 0.25},
 ('Kuwait', 'Nepal'): {'Kuwait': 0.25, 'Nepal': 0.75},
 ('Malaysia', 'Qatar'): {'Malaysia': 0.25, 'Qatar': 0.75},
 ('Nepal', 'Singapore'): {'Nepal': 0.6666666666666666,
  'Singapore': 0.3333333333333333},
 ('Bermuda', 'United States of America'): {'Bermuda': 0.4,
  'United States of America': 0.6},
 ('Canada', 'Cayman Islands'): {'Canada': 1.0, 'Cayman Islands': 0.0},
 ('Cayman Islands', 'United States of America'): {'Cayman Islands': 0.0,
  'United States of America': 1.0},
 ('Canada', 'United States of America'): {'Canada': 0.3,
  'United States of America': 0.7},
 ('Bermuda', 'Cayman Islands'): {'Bermuda': 0.8888888888888888,
  'Cayman Islands': 0.1111111111111111},
 ('Nepal', 'Zimbabwe'): {'Nepal': 0.0, 'Zimbabwe': 1.0},
 ('Malaysia', 'Vanuatu'): {'Malaysia': 0.5, 'Vanuatu': 0.5},
 ('Singapore', 'Zimbabwe'): {'Singapore': 0.3333333333333333,
  'Zimbabwe': 0.6666666666666666},
 ('Nepal', 'Oman'): {'Nepal': 0.75, 'Oman': 0.25},
 ('Scotland', 'Singapore'): {'Scotland': 0.0, 'Singapore': 1.0},
 ('Namibia', 'Netherlands'): {'Namibia': 0.25, 'Netherlands': 0.75},
 ('Jersey', 'Nigeria'): {'Jersey': 1.0, 'Nigeria': 0.0},
 ('Bermuda', 'Papua New Guinea'): {'Bermuda': 0.0, 'Papua New Guinea': 1.0},
 ('Canada', 'Jersey'): {'Canada': 1.0, 'Jersey': 0.0},
 ('Bermuda', 'Singapore'): {'Bermuda': 0.0, 'Singapore': 1.0},
 ('Namibia', 'Papua New Guinea'): {'Namibia': 0.3333333333333333,
  'Papua New Guinea': 0.6666666666666666},
 ('Papua New Guinea', 'Scotland'): {'Papua New Guinea': 0.0, 'Scotland': 1.0},
 ('Canada', 'Nigeria'): {'Canada': 1.0, 'Nigeria': 0.0},
 ('Bermuda', 'Kenya'): {'Bermuda': 0.0, 'Kenya': 1.0},
 ('Namibia', 'Scotland'): {'Namibia': 0.75, 'Scotland': 0.25},
 ('Netherlands', 'Singapore'): {'Netherlands': 1.0, 'Singapore': 0.0},
 ('Jersey', 'United Arab Emirates'): {'Jersey': 1.0,
  'United Arab Emirates': 0.0},
 ('Kenya', 'Singapore'): {'Kenya': 1.0, 'Singapore': 0.0},
 ('Bermuda', 'Namibia'): {'Bermuda': 0.0, 'Namibia': 1.0},
 ('Hong Kong', 'Jersey'): {'Hong Kong': 1.0, 'Jersey': 0.0},
 ('Nigeria', 'Oman'): {'Nigeria': 0.0, 'Oman': 1.0},
 ('Netherlands', 'Papua New Guinea'): {'Netherlands': 0.6666666666666666,
  'Papua New Guinea': 0.3333333333333333},
 ('Canada', 'Hong Kong'): {'Canada': 0.0, 'Hong Kong': 1.0},
 ('Nigeria', 'United Arab Emirates'): {'Nigeria': 0.0,
  'United Arab Emirates': 1.0},
 ('Papua New Guinea', 'Singapore'): {'Papua New Guinea': 0.6666666666666666,
  'Singapore': 0.3333333333333333},
 ('Ireland', 'Jersey'): {'Ireland': 1.0, 'Jersey': 0.0},
 ('Kenya', 'Namibia'): {'Kenya': 0.0, 'Namibia': 1.0},
 ('Portugal', 'Spain'): {'Portugal': 0.0, 'Spain': 1.0},
 ('Canada', 'Oman'): {'Canada': 0.5714285714285714,
  'Oman': 0.42857142857142855},
 ('Gibraltar', 'Portugal'): {'Gibraltar': 0.0, 'Portugal': 1.0},
 ('Gibraltar', 'Spain'): {'Gibraltar': 0.0, 'Spain': 1.0},
 ('Ireland', 'Nigeria'): {'Ireland': 1.0, 'Nigeria': 0.0},
 ('Bermuda', 'Netherlands'): {'Bermuda': 0.0, 'Netherlands': 1.0},
 ('Namibia', 'Singapore'): {'Namibia': 1.0, 'Singapore': 0.0},
 ('Canada', 'United Arab Emirates'): {'Canada': 0.0,
  'United Arab Emirates': 1.0},
 ('Jersey', 'Oman'): {'Jersey': 1.0, 'Oman': 0.0},
 ('Hong Kong', 'Nigeria'): {'Hong Kong': 1.0, 'Nigeria': 0.0},
 ('Kenya', 'Papua New Guinea'): {'Kenya': 0.0, 'Papua New Guinea': 1.0},
 ('Namibia', 'Oman'): {'Namibia': 0.6666666666666666,
  'Oman': 0.3333333333333333},
 ('Ireland', 'Namibia'): {'Ireland': 0.5, 'Namibia': 0.5},
 ('Bhutan', 'Nepal'): {'Bhutan': 0.0, 'Nepal': 1.0},
 ('Maldives', 'Nepal'): {'Maldives': 0.0, 'Nepal': 1.0},
 ('Bhutan', 'Maldives'): {'Bhutan': 0.5, 'Maldives': 0.5},
 ('Hong Kong', 'Malaysia'): {'Hong Kong': 0.42105263157894735,
  'Malaysia': 0.5789473684210527},
 ('Bahrain', 'Qatar'): {'Bahrain': 0.4, 'Qatar': 0.6},
 ('Saudi Arabia', 'United Arab Emirates'): {'Saudi Arabia': 0.3333333333333333,
  'United Arab Emirates': 0.6666666666666666},
 ('Maldives', 'Oman'): {'Maldives': 0.0, 'Oman': 1.0},
 ('Iran', 'Kuwait'): {'Iran': 0.0, 'Kuwait': 1.0},
 ('Bahrain', 'Kuwait'): {'Bahrain': 0.25, 'Kuwait': 0.75},
 ('Qatar', 'United Arab Emirates'): {'Qatar': 0.0,
  'United Arab Emirates': 1.0},
 ('Kuwait', 'United Arab Emirates'): {'Kuwait': 0.16666666666666666,
  'United Arab Emirates': 0.8333333333333334},
 ('Singapore', 'Thailand'): {'Singapore': 0.75, 'Thailand': 0.25},
 ('Hong Kong', 'Thailand'): {'Hong Kong': 1.0, 'Thailand': 0.0},
 ('Hong Kong', 'Singapore'): {'Hong Kong': 0.8333333333333334,
  'Singapore': 0.16666666666666666},
 ('Nepal', 'Thailand'): {'Nepal': 1.0, 'Thailand': 0.0},
 ('Germany', 'Spain'): {'Germany': 0.42857142857142855,
  'Spain': 0.5714285714285714},
 ('Guernsey', 'Isle of Man'): {'Guernsey': 1.0, 'Isle of Man': 0.0},
 ('Belgium', 'Luxembourg'): {'Belgium': 1.0, 'Luxembourg': 0.0},
 ('Belgium', 'Czech Republic'): {'Belgium': 1.0, 'Czech Republic': 0.0},
 ('Bulgaria', 'Romania'): {'Bulgaria': 0.14285714285714285,
  'Romania': 0.8571428571428571},
 ('Malaysia', 'Netherlands'): {'Malaysia': 0.0, 'Netherlands': 1.0},
 ('Czech Republic', 'Luxembourg'): {'Czech Republic': 0.75,
  'Luxembourg': 0.25},
 ('Austria', 'Czech Republic'): {'Austria': 0.8333333333333334,
  'Czech Republic': 0.16666666666666666},
 ('Austria', 'Luxembourg'): {'Austria': 0.8, 'Luxembourg': 0.2},
 ('Greece', 'Romania'): {'Greece': 0.0, 'Romania': 1.0},
 ('Romania', 'Serbia'): {'Romania': 1.0, 'Serbia': 0.0},
 ('Greece', 'Serbia'): {'Greece': 1.0, 'Serbia': 0.0},
 ('Belgium', 'Malta'): {'Belgium': 0.8, 'Malta': 0.2},
 ('Ireland', 'South Africa'): {'Ireland': 0.14285714285714285,
  'South Africa': 0.8571428571428571},
 ('France', 'Norway'): {'France': 0.5, 'Norway': 0.5},
 ('France', 'Germany'): {'France': 0.0, 'Germany': 1.0},
 ('Denmark', 'Sweden'): {'Denmark': 0.5, 'Sweden': 0.5},
 ('Ghana', 'Rwanda'): {'Ghana': 0.42857142857142855,
  'Rwanda': 0.5714285714285714},
 ('Gibraltar', 'Malta'): {'Gibraltar': 0.25, 'Malta': 0.75},
 ('Finland', 'Sweden'): {'Finland': 0.5, 'Sweden': 0.5},
 ('Czech Republic', 'Hungary'): {'Czech Republic': 0.75, 'Hungary': 0.25},
 ('Bulgaria', 'Luxembourg'): {'Bulgaria': 0.0, 'Luxembourg': 1.0},
 ('Czech Republic', 'Romania'): {'Czech Republic': 0.3333333333333333,
  'Romania': 0.6666666666666666},
 ('Bulgaria', 'Malta'): {'Bulgaria': 0.0, 'Malta': 1.0},
 ('Hungary', 'Romania'): {'Hungary': 0.2, 'Romania': 0.8},
 ('Malta', 'Romania'): {'Malta': 0.5, 'Romania': 0.5},
 ('Hungary', 'Luxembourg'): {'Hungary': 0.6666666666666666,
  'Luxembourg': 0.3333333333333333},
 ('Hungary', 'Malta'): {'Hungary': 0.75, 'Malta': 0.25},
 ('Luxembourg', 'Romania'): {'Luxembourg': 0.25, 'Romania': 0.75},
 ('Kenya', 'Nigeria'): {'Kenya': 0.7857142857142857,
  'Nigeria': 0.21428571428571427},
 ('Nigeria', 'Uganda'): {'Nigeria': 0.0, 'Uganda': 1.0},
 ('Cyprus', 'Estonia'): {'Cyprus': 0.5555555555555556,
  'Estonia': 0.4444444444444444},
 ('Cyprus', 'Isle of Man'): {'Cyprus': 0.0, 'Isle of Man': 1.0},
 ('Estonia', 'Isle of Man'): {'Estonia': 0.0, 'Isle of Man': 1.0},
 ('Ghana', 'Seychelles'): {'Ghana': 1.0, 'Seychelles': 0.0},
 ('Malawi', 'Uganda'): {'Malawi': 0.0, 'Uganda': 1.0},
 ('Lesotho', 'Seychelles'): {'Lesotho': 0.0, 'Seychelles': 1.0},
 ('Rwanda', 'Uganda'): {'Rwanda': 0.0, 'Uganda': 1.0},
 ('Bangladesh', 'Scotland'): {'Bangladesh': 0.0, 'Scotland': 1.0},
 ('Malawi', 'Swaziland'): {'Malawi': 1.0, 'Swaziland': 0.0},
 ('Oman', 'Papua New Guinea'): {'Oman': 0.8, 'Papua New Guinea': 0.2},
 ('Namibia', 'Sri Lanka'): {'Namibia': 0.5, 'Sri Lanka': 0.5},
 ('Swaziland', 'Uganda'): {'Swaziland': 0.0, 'Uganda': 1.0},
 ('Lesotho', 'Uganda'): {'Lesotho': 0.0, 'Uganda': 1.0},
 ('Ghana', 'Malawi'): {'Ghana': 0.5, 'Malawi': 0.5},
 ('Nigeria', 'Sierra Leone'): {'Nigeria': 0.9, 'Sierra Leone': 0.1},
 ('Ghana', 'Swaziland'): {'Ghana': 1.0, 'Swaziland': 0.0},
 ('Malawi', 'Seychelles'): {'Malawi': 1.0, 'Seychelles': 0.0},
 ('Seychelles', 'Swaziland'): {'Seychelles': 1.0, 'Swaziland': 0.0},
 ('Lesotho', 'Rwanda'): {'Lesotho': 0.0, 'Rwanda': 1.0},
 ('Bangladesh', 'Papua New Guinea'): {'Bangladesh': 1.0,
  'Papua New Guinea': 0.0},
 ('Gibraltar', 'Switzerland'): {'Gibraltar': 0.0, 'Switzerland': 1.0},
 ('Rwanda', 'Swaziland'): {'Rwanda': 1.0, 'Swaziland': 0.0},
 ('Malawi', 'Rwanda'): {'Malawi': 0.4444444444444444,
  'Rwanda': 0.5555555555555556},
 ('Seychelles', 'Uganda'): {'Seychelles': 0.0, 'Uganda': 1.0},
 ('Bulgaria', 'Switzerland'): {'Bulgaria': 0.0, 'Switzerland': 1.0},
 ('Maldives', 'Saudi Arabia'): {'Maldives': 0.0, 'Saudi Arabia': 1.0},
 ('Malta', 'Switzerland'): {'Malta': 0.25, 'Switzerland': 0.75},
 ('Maldives', 'Qatar'): {'Maldives': 0.0, 'Qatar': 1.0},
 ('Bulgaria', 'Gibraltar'): {'Bulgaria': 0.5714285714285714,