In [2]:
# We will define a toss win as a team winning both the toss AND the match.
## This cell will compute tosses.

import pandas as pd

df = pd.read_csv("data/t20i_matches_clean.csv")

total_matches=len(df)

match_and_toss=len(df[(df['toss_winner'] == df['winner'])])

toss_pct=round((match_and_toss / total_matches)*100 , 3)

print('The percent of matches won by the team who won the toss is '+str(toss_pct) +'% overall')

The percent of matches won by the team who won the toss is 50.204% overall

no significant effect

In [3]:
##This cell will compute whether toss decision has an effect

bat=len(df[(df['toss_decision'] == 'bat')])
ball=len(df[(df['toss_decision'] == 'field')])

bat_win=len(df[
    (df['toss_decision'] == 'bat') &
    (df['toss_winner'] == df['winner'])  
               ])
ball_win=len(df[
    (df['toss_decision'] == 'field') &
    (df['toss_winner'] == df['winner'])  
               ])

bat_win_pct=round((bat_win/ bat )*100 , 3)
ball_win_pct=round((ball_win/ ball )*100 , 3)

print('The percentage of matches won by the team who won the toss and elected to bat is '+str(bat_win_pct)+'%')
print('The percentage of matches won by the team who won the toss and elected to field is '+str(ball_win_pct)+'%')

The percentage of matches won by the team who won the toss and elected to bat is 49.077%
The percentage of matches won by the team who won the toss and elected to field is 51.167%

no significant effect

In [4]:
#This one will look at venues
# add helper column: did toss winner also win match?
df["toss_win"] = (df["toss_winner"] == df["winner"])

# group by venue
venue_stats = (
    df.groupby("venue")
      .agg(
          matches=("venue", "count"),
          toss_win_rate=("toss_win", "mean")
      )
      .reset_index()
)

# convert rate to percentage
venue_stats["toss_win_rate"] = venue_stats["toss_win_rate"] * 100

# drop small sample venues
venue_stats = venue_stats[venue_stats["matches"] >= 10]

# sort by toss impact
venue_stats = venue_stats.sort_values(by="toss_win_rate", ascending=False)

venue_stats.head(100)

                                            venue  matches  toss_win_rate
128           King George V Sports Ground, Castel       14      78.571429
123                   Kensington Oval, Bridgetown       16      75.000000
68                           Entebbe Cricket Oval       19      73.684211
268                            TCA Oval, Blantyre       14      71.428571
76                        Gaddafi Stadium, Lahore       14      71.428571
..                                            ...      ...            ...
209                           Roma Cricket Ground       12      25.000000
236                    Simar Cricket Ground, Rome       12      25.000000
210  Royal Brussels Cricket Club Ground, Waterloo       10      20.000000
24                         Bellerive Oval, Hobart       11      18.181818
3                                   Adelaide Oval       12       8.333333

[96 rows x 3 columns]

In [22]:
#we will count matches played for each team

played = {}

for col, row in df.iterrows():
    team1 = row["team1"]
    team2 = row["team2"]

    if team1 not in played:
        played[team1] = 0
    played[team1] += 1

    if team2 not in played:
        played[team2] = 0
    played[team2] += 1

print(played)

#count wins

won={}
for col, row in df.iterrows():
    team = row["winner"]

    if team not in won:
        won[team] = 0
    won[team] += 1

for team in played:
    if team not in won:
        won[team]=0
    
#compute win percent
wpct={}
for team in played:
    if team not in won:
        wpct[team]=0
    else:
        wpct[team]= ((str(round(((won[team] / played[team]) * 100),3))) +'%')

wpct

{'New Zealand': 223, 'Australia': 207, 'England': 199, 'South Africa': 203, 'Sri Lanka': 200, 'Pakistan': 262, 'India': 237, 'West Indies': 216, 'Kenya': 92, 'Bangladesh': 185, 'Scotland': 85, 'Zimbabwe': 161, 'Bermuda': 45, 'Netherlands': 108, 'Ireland': 134, 'Canada': 69, 'Hong Kong': 106, 'Nepal': 100, 'United Arab Emirates': 117, 'Papua New Guinea': 57, 'Oman': 95, 'ICC World XI': 4, 'United States of America': 48, 'Vanuatu': 31, 'Philippines': 33, 'Ghana': 37, 'Namibia': 82, 'Uganda': 102, 'Botswana': 45, 'Nigeria': 79, 'Germany': 56, 'Italy': 31, 'Guernsey': 33, 'Jersey': 44, 'Norway': 43, 'Denmark': 39, 'Malaysia': 98, 'Thailand': 50, 'Maldives': 37, 'Kuwait': 64, 'Singapore': 61, 'Qatar': 52, 'Cayman Islands': 35, 'Spain': 36, 'Portugal': 30, 'Gibraltar': 47, 'Bhutan': 30, 'Bahrain': 90, 'Saudi Arabia': 48, 'Iran': 1, 'Isle of Man': 19, 'Belgium': 35, 'Luxembourg': 40, 'Czech Republic': 35, 'Bulgaria': 46, 'Romania': 53, 'Austria': 58, 'Greece': 9, 'Serbia': 32, 'Malta': 66, 'France': 32, 'Sweden': 28, 'Rwanda': 83, 'Finland': 29, 'Hungary': 36, 'Estonia': 29, 'Cyprus': 31, 'Seychelles': 12, 'Malawi': 36, 'Lesotho': 11, 'Swaziland': 5, 'Sierra Leone': 29, 'Switzerland': 28, 'Tanzania': 67, 'Mozambique': 21, 'Cameroon': 15, 'Belize': 12, 'Panama': 22, 'Bahamas': 28, 'Argentina': 21, 'Israel': 8, 'Turkey': 15, 'Croatia': 23, 'Slovenia': 15, 'Samoa': 23, 'Cook Islands': 16, 'Fiji': 11, 'Japan': 46, 'Indonesia': 75, 'South Korea': 17, 'Mali': 9, 'St Helena': 8, 'Gambia': 9, 'Eswatini': 13, 'China': 9, 'Myanmar': 25, 'Mongolia': 13, 'Chile': 2, 'Mexico': 18, 'Cambodia': 28, 'Costa Rica': 8, 'Brazil': 9, 'Ivory Coast': 5, 'Suriname': 8, 'Turks and Caicos Island': 4, 'Timor-Leste': 8}

{'New Zealand': '56.054%',
 'Australia': '58.454%',
 'England': '54.774%',
 'South Africa': '54.187%',
 'Sri Lanka': '45.0%',
 'Pakistan': '59.542%',
 'India': '69.62%',
 'West Indies': '43.981%',
 'Kenya': '53.261%',
 'Bangladesh': '38.919%',
 'Scotland': '49.412%',
 'Zimbabwe': '41.615%',
 'Bermuda': '68.889%',
 'Netherlands': '52.778%',
 'Ireland': '46.269%',
 'Canada': '59.42%',
 'Hong Kong': '47.17%',
 'Nepal': '62.0%',
 'United Arab Emirates': '56.41%',
 'Papua New Guinea': '50.877%',
 'Oman': '49.474%',
 'ICC World XI': '25.0%',
 'United States of America': '58.333%',
 'Vanuatu': '38.71%',
 'Philippines': '42.424%',
 'Ghana': '35.135%',
 'Namibia': '60.976%',
 'Uganda': '79.412%',
 'Botswana': '31.111%',
 'Nigeria': '46.835%',
 'Germany': '58.929%',
 'Italy': '64.516%',
 'Guernsey': '51.515%',
 'Jersey': '65.909%',
 'Norway': '53.488%',
 'Denmark': '43.59%',
 'Malaysia': '57.143%',
 'Thailand': '42.0%',
 'Maldives': '24.324%',
 'Kuwait': '59.375%',
 'Singapore': '36.066%',
 'Qatar': '50.0%',
 'Cayman Islands': '40.0%',
 'Spain': '80.556%',
 'Portugal': '70.0%',
 'Gibraltar': '31.915%',
 'Bhutan': '33.333%',
 'Bahrain': '62.222%',
 'Saudi Arabia': '54.167%',
 'Iran': '0.0%',
 'Isle of Man': '52.632%',
 'Belgium': '57.143%',
 'Luxembourg': '32.5%',
 'Czech Republic': '45.714%',
 'Bulgaria': '34.783%',
 'Romania': '60.377%',
 'Austria': '74.138%',
 'Greece': '11.111%',
 'Serbia': '28.125%',
 'Malta': '40.909%',
 'France': '46.875%',
 'Sweden': '39.286%',
 'Rwanda': '28.916%',
 'Finland': '44.828%',
 'Hungary': '47.222%',
 'Estonia': '37.931%',
 'Cyprus': '61.29%',
 'Seychelles': '16.667%',
 'Malawi': '38.889%',
 'Lesotho': '18.182%',
 'Swaziland': '0.0%',
 'Sierra Leone': '41.379%',
 'Switzerland': '64.286%',
 'Tanzania': '56.716%',
 'Mozambique': '38.095%',
 'Cameroon': '13.333%',
 'Belize': '25.0%',
 'Panama': '31.818%',
 'Bahamas': '28.571%',
 'Argentina': '47.619%',
 'Israel': '37.5%',
 'Turkey': '13.333%',
 'Croatia': '17.391%',
 'Slovenia': '6.667%',
 'Samoa': '21.739%',
 'Cook Islands': '50.0%',
 'Fiji': '54.545%',
 'Japan': '65.217%',
 'Indonesia': '49.333%',
 'South Korea': '11.765%',
 'Mali': '0.0%',
 'St Helena': '25.0%',
 'Gambia': '11.111%',
 'Eswatini': '46.154%',
 'China': '11.111%',
 'Myanmar': '20.0%',
 'Mongolia': '0.0%',
 'Chile': '0.0%',
 'Mexico': '44.444%',
 'Cambodia': '42.857%',
 'Costa Rica': '25.0%',
 'Brazil': '33.333%',
 'Ivory Coast': '0.0%',
 'Suriname': '25.0%',
 'Turks and Caicos Island': '25.0%',
 'Timor-Leste': '0.0%'}

In [26]:
##compile the 3 dicts into one dataframe
rows=[]
for team in played:
    r = {
    "team": team,
    "matches_played": played[team],
    "wins": won[team],
    "win_rate": wpct[team]
}
    rows.append(r)

df1=pd.DataFrame(rows)
df1

                        team  matches_played  wins win_rate
0                New Zealand             223   125  56.054%
1                  Australia             207   121  58.454%
2                    England             199   109  54.774%
3               South Africa             203   110  54.187%
4                  Sri Lanka             200    90    45.0%
..                       ...             ...   ...      ...
101                   Brazil               9     3  33.333%
102              Ivory Coast               5     0     0.0%
103                 Suriname               8     2    25.0%
104  Turks and Caicos Island               4     1    25.0%
105              Timor-Leste               8     0     0.0%

[106 rows x 4 columns]